### ISSUE TITLE
ethereum signature

### ISSUE THREAD

**Issue by redDwarf03** [C0MM4ND/dart-ecdsa#1]
Hello
I would like to sign using ECDSA but I need the variable "v" for the recovery identifier to obtain a signature {r, s, v}
could you help me please ?

**Comment by c0mm4nd** [comment]
~~The v value you need is stored here https://github.com/C0MM4ND/dart-ecdsa/blob/7ba609ccc56ef64b11820506924d0c353253815c/lib/src/deterministic.dart#L45~~

https://bitcoin.stackexchange.com/questions/38351/ecdsa-v-r-s-what-is-v

https://github.com/wizardofozzie/pybitcointools/blob/9f79e2aa967a5c10a5a8ba16030c9b6fe0388c0e/bitcoin/main.py#L541-L542

https://github.com/C0MM4ND/dart-ecdsa/blob/7ba609ccc56ef64b11820506924d0c353253815c/lib/src/deterministic.dart#L14

So we can get it inside the deterministicSign function
```dart
  var r = p.X % priv.curve.n;
  if (r.sign == 0) {
    throw Exception('calculated R is zero');
  }
  // add the following 2 lines
  var y = p.Y % priv.curve.n; 
  var v = 27+ (y % 2);
  ...
  // finally return the v value with r s
```

But I have no good idea on how to gracefully export it without changing Signature class and the header of deterministicSign function. I have to add a new function & a new Signature class for the v value.

**Comment by redDwarf03** [comment]
thank you for you answer
is it possible for you to add this please ?

**Comment by c0mm4nd** [comment]
try v0.0.4

```dart 
var sig = ethereumSign(priv, hash);
var hex = sig.toEthCompactHex(); // only toEthXXX func will bring V value
var v = sig.getV(); // or getEIP155V(chainID)
var sig2 = EthSignature.fromEthCompactHex(hex); //  only fromEthXXX func will carry V value, other constructor works as a normal Signature
```

**Comment by redDwarf03** [comment]
it works for me. thx !
