### ISSUE TITLE
Wrong `v` value on ethereum signature

### ISSUE THREAD

**Issue by fonstack** [C0MM4ND/dart-ecdsa#6]
Hey @c0mm4nd 

I've using your library and I just realized there is something wrong with the calculation of `v`.

In one signature it should return `v = 0` but instead is returning `v = 1`. This is basically changing the end of the signature from `...1b` to `...1c`. Any idea why is this happening?

**Comment by c0mm4nd** [comment]
The eth sign test passed as shown in commit 8b87d9f47fcba396d0ef4d4712c160375d3754af 
Is there any newer standard for Ethereum signature?

If possible, could you show me your data, including the content hash, privKey, and the expected signature helping me debug?

**Comment by fonstack** [comment]
I'm testing with this params:

* private key -> e4d7f99de955728c9921a3de9f2bcdaeb54938da0b1179fdd2275d7ce09dd002
* hash hex to be signed -> b6e16d27ac5ab427a7f68900ac5559ce272dc6c37c82b3e052246c82244c50e4 ("Hello, world!")

* expected signature -> 0x96df6608b777f7642e741b97843475ab29981bca31c2f47d657b43ff7b460d2148def6cd02fb866ac45f736dcc6829f1ca34c1f112805eae0c73981aecee94281b with `v = 0` (the last `1b`)

but I'm getting -> 
0x96df6608b777f7642e741b97843475ab29981bca31c2f47d657b43ff7b460d2148def6cd02fb866ac45f736dcc6829f1ca34c1f112805eae0c73981aecee942801

If I use `getV()` I'm getting `28` => `1c`
and the expected is `getV() = 27` => `1b`

**Comment by fonstack** [comment]
You can also take a look at this playground using another library and it's indeed returning the signature with `...1b`

https://zapp.run/edit/dart-zow060qox06?entry=lib/main.dart&file=lib/main.dart

**Comment by c0mm4nd** [comment]
https://github.com/simolus3/web3dart/blob/a97de62fbe8ccc04c29d3c726484cccd5a9522fe/lib/src/crypto/secp256k1.dart#L95C1-L112C49

https://github.com/simolus3/web3dart/issues/240

The result from web3dart is not convincing, please try other lib to validate.

**Comment by fonstack** [comment]
I can also provide you this JS (using viem) playground with the exact same result @c0mm4nd 

https://stackblitz.com/edit/node-js-playground-qsoa9p?file=index.js

Please let me know if you need furthers assistance. This package is pretty important to us and we need this to continue our development!

**Comment by fonstack** [comment]
Hey @c0mm4nd please take a look at teammate’s @josher8a PR. He is solving the issue based on this https://ethereum.stackexchange.com/a/53182

**Comment by c0mm4nd** [comment]
Thank you and your great team. I have already merged the PR and published a new version on pub.dev https://pub.dev/packages/ecdsa/versions/0.1.1

**Comment by fonstack** [comment]
I'll close this since it's already solved, thanks sir @c0mm4nd 

cc: kudos to @josher8a :3
